title: Open cranio maxillofacial encyclopedia.
author: kosheniatko
email: kosheniatko1994@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open cranio maxillofacial encyclopedia for everybody.

# social links
twitter_username: N/A
github_username:  kosheniatko

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
